network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      dhcp4: no
      dhcp6: no
    enp2s0:
      dhcp4: no
      dhcp6: no
 
  bridges:
    br0:
      interfaces: [enp1s0, enp2s0]
      dhcp4: no
      parameters:
        stp: false
        forward-delay: 0